version: "3.7"

services:
    php:
        image: php
        command: php -S 0.0.0.0:8080 -t .
        ports:
            - 8080:8080
        working_dir: /design-pattens
        volumes:
            - ./:/design-pattens
        container_name: php
    composer:
        image: composer
        command: install
        working_dir: /design-patterns
        volumes:
            - ./:/design-patterns
        container_name: composer